cd deployer
call mvn_deploy_declaration-mrh-volcambriolage.cmd
call mvn_deploy_declaration-mrh-tempeteetgrele.cmd
call mvn_deploy_declaration-mrh-dommageelectrique.cmd
call mvn_deploy_declaration-mrh-degatsdeseaux.cmd
call mvn_deploy_declaration-mrh-brisdeglace.cmd
call mvn_deploy_declaration-auto-vol.cmd
call mvn_deploy_declaration-auto-vandalisme.cmd
call mvn_deploy_declaration-auto-incendie.cmd
call mvn_deploy_declaration-auto-accident.cmd
cd ..
