// Generated 12 mars 2007 23:20:24 by Hibernate Tools 3.2.0.b9
package fr.alliance.docalliance.model;

/**
 * Destinataires generated by hbm2java
 */
public class Destinataire extends AbstractTO {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1928376013432407792L;
	
	private DestinataireId id;
	private AdresseMail adresseMail;
	private Mail mail;

	public Destinataire() {
		super();
	}

	public Destinataire(DestinataireId id) {
		this.id = id;
	}

	public DestinataireId getId() {
		return this.id;
	}

	public void setId(DestinataireId id) {
		this.id = id;
	}

	public AdresseMail getAdresseMail() {
		return adresseMail;
	}

	public void setAdresseMail(AdresseMail adresseMail) {
		this.adresseMail = adresseMail;
	}

	public Mail getMail() {
		return mail;
	}

	public void setMail(Mail mail) {
		this.mail = mail;
	}
}