// Generated 12 mars 2007 23:20:24 by Hibernate Tools 3.2.0.b9
package fr.alliance.docalliance.model;

import java.util.HashSet;
import java.util.Set;

/**
 * Adressemail generated by hbm2java
 */
public class AdresseMail extends AbstractTO {

	/**
	 * 
	 */
	private static final long serialVersionUID = 9095260972994448934L;
	
	private int idAdresseMail;
	private String firstName;
	private String lastName;
	private String adresseMail;
	private boolean active;
	private Set users = new HashSet(0);
	private Set mails = new HashSet(0);
	private Set destinataires = new HashSet(0);
	
	public AdresseMail() {
		super();
	}

	public int getIdAdresseMail() {
		return this.idAdresseMail;
	}

	public void setIdAdresseMail(int idAdresseMail) {
		this.idAdresseMail = idAdresseMail;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getAdresseMail() {
		return this.adresseMail;
	}

	public void setAdresseMail(String adresseMail) {
		this.adresseMail = adresseMail;
	}

	public boolean getActive() {
		return this.active;
	}

	public void setActive(boolean active) {
		this.active = active;
	}

	public Set getDestinataires() {
		return destinataires;
	}

	public void setDestinataires(Set destinataires) {
		this.destinataires = destinataires;
	}

	public Set getMails() {
		return mails;
	}

	public void setMails(Set mails) {
		this.mails = mails;
	}

	public Set getUsers() {
		return users;
	}

	public void setUsers(Set users) {
		this.users = users;
	}
}